<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="0"
            tests="0">

  <testsuite name="test2"
    errors="0" failures="0" hostname="" id="" package="test2" skipped="0"
    tests="0" time="0.000" timestamp="Thu, 15 Mar 2018 21:19:26 GMT">
  

  
    <system-err>
        Error while running [Tests / New Name Test]:

  TypeError: functions.nameTest is not a function
    at Object.New Name Test (C:\Users\Randy\Documents\DevMtn\Projects\Enter-Wanted\tests\tests.js:15:19)
    at Module.call (C:\Users\Randy\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\module.js:62:34)
    at C:\Users\Randy\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (C:\Users\Randy\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\Randy\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\Randy\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:796:13)
    at C:\Users\Randy\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:556:49
    at runSingle (C:\Users\Randy\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:137:13)
    at flush (C:\Users\Randy\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    </system-err>
  

  
  </testsuite>
</testsuites>
